global:
  scrape_interval: 1s
  evaluation_interval: 15s

# Alerting specifies settings related to the Alertmanager
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            # Alertmanager's default port is 9093
            - localhost:9093

rule_files:
  - /etc/prometheus/rules/rules.yml

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: node
    static_configs:
      - targets: ["node_exporter:9100"]

  - job_name: gpu
    static_configs:
      - targets: ["gpu_exporter:9400"]

  - job_name: iris_classifier
    static_configs:
      - targets: ["iris:8000"]

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
